DO $$ BEGIN
  CREATE ROLE farmos_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE ROLE farmos_app LOGIN PASSWORD 'local-dev-only' IN ROLE farmos_runtime;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
